// <auto-generated />
using System;
using Happy5SocialMedia.Activity.Domain.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Happy5SocialMedia.Activity.Migrations
{
    [DbContext(typeof(Happy5socialmedia_ActivityContext))]
    [Migration("20190908075729_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Happy5SocialMedia.Activity.Domain.Model.ActivityStatus", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("ActivityStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47334304-9f19-467f-9646-429d29943a81"),
                            Description = "Accepted",
                            Name = "Accepted"
                        },
                        new
                        {
                            Id = new Guid("1a07418e-40b1-491b-bbc3-2273874f8b77"),
                            Description = "Request",
                            Name = "Request"
                        },
                        new
                        {
                            Id = new Guid("02a2815b-53bf-4c7e-a15e-9319389fa7cb"),
                            Description = "Pending",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = new Guid("62dbf46e-f666-4158-a041-db4610afb3f5"),
                            Description = "Declined",
                            Name = "Declined"
                        });
                });

            modelBuilder.Entity("Happy5SocialMedia.Activity.Domain.Model.FriendRelationship", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("FriendRequestId");

                    b.Property<Guid>("Status");

                    b.HasKey("Id");

                    b.HasIndex("FriendRequestId");

                    b.HasIndex("Status");

                    b.ToTable("FriendRelationship");
                });

            modelBuilder.Entity("Happy5SocialMedia.Activity.Domain.Model.FriendRequest", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid?>("Status");

                    b.Property<Guid>("UserReciever");

                    b.Property<Guid>("UserSender");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("FriendRequest");
                });

            modelBuilder.Entity("Happy5SocialMedia.Activity.Domain.Model.FriendRelationship", b =>
                {
                    b.HasOne("Happy5SocialMedia.Activity.Domain.Model.FriendRequest", "FriendRequest")
                        .WithMany("FriendRelationship")
                        .HasForeignKey("FriendRequestId")
                        .HasConstraintName("FK_FriendRelationship_FriendRequest");

                    b.HasOne("Happy5SocialMedia.Activity.Domain.Model.ActivityStatus", "StatusNavigation")
                        .WithMany("FriendRelationship")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK_FriendRelationship_ActivityStatus");
                });

            modelBuilder.Entity("Happy5SocialMedia.Activity.Domain.Model.FriendRequest", b =>
                {
                    b.HasOne("Happy5SocialMedia.Activity.Domain.Model.ActivityStatus", "StatusNavigation")
                        .WithMany("FriendRequest")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK_FriendRequest_ActivityStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
